### ISSUE TITLE
I can't push updates to the repository

### ISSUE THREAD

**Issue by thepablodh** [mpakin1/jackTower#1]
Micah,

Can you give me push permissions? Thanks.
(Not that I've gotten anything close to the intended results yet)

Paul

**Comment by mpakin1** [comment]
I think we need to fork the repository to make changes.  https://help.github.com/articles/fork-a-repo/

V/r,
Capt Micah Akin
mpakin1@nps.edumailto:mpakin1@nps.edu

On Sep 17, 2015, at 4:33 PM, thepablodh <notifications@github.com<mailto:notifications@github.com>> wrote:

Micah,

Can you give me push permissions? Thanks.
(Not that I've gotten anything close to the intended results yet)

Paul
